import { Metadata } from "next";
import styles from "./page.module.scss";
import { PrimaryButton } from "../components/UI/PrimaryButton/PrimaryButton";
import Link from "next/link";
import Image from "next/image";
import Logo from "@/static/icons/logo.svg";
export const metadata: Metadata = {
  title: "Spark",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className={styles.container}>
      <div className={styles.title}>
        <Image src={Logo} alt="logo" />
      </div>
      <Link className={styles.link} href="/games">
        <PrimaryButton variant="primary">Играть</PrimaryButton>
      </Link>
      <PrimaryButton>Обратная связь</PrimaryButton>
    </div>
  );
}
